theme: jekyll-theme-minimal
title: StudyMate Documentation
description: Документация проекта StudyMate
show_downloads: true

# Build settings
markdown: kramdown
plugins:
  - jekyll-feed
  - jekyll-seo-tag

# Exclude from processing
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor
  - .gitignore 