name: UI Tests

on:
  pull_request:
    branches: [ main, master ]

jobs:
  test:
    name: Run UI Tests
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: gradle
    
    - name: Set up Android SDK
      uses: android-actions/setup-android@v3
    
    - name: Accept Android Licenses
      run: |
        yes | sdkmanager --licenses
        sdkmanager "platform-tools" "platforms;android-29" "build-tools;29.0.3" "system-images;android-29;google_apis;x86_64"
    
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    
    - name: Run UI Tests
      uses: malinskiy/action-android@master
      with:
        cmd: ./gradlew connectedAndroidTest
        api-level: 28
        target: google_apis
        arch: x86_64
        profile: Nexus 6
      env:
        ANDROID_EMULATOR_HEADLESS: 1
        ANDROID_EMULATOR_QUICK_BOOT: 1
