name: UI Tests

on:
  pull_request:
    branches: [ main, master ]

jobs:
  test:
    name: Run UI Tests
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: gradle
    
    - name: Set up Android SDK
      uses: android-actions/setup-android@v3
    
    - name: Accept Android Licenses
      run: |
        yes | sdkmanager --licenses
        sdkmanager "platform-tools" "platforms;android-28" "build-tools;28.0.3" "system-images;android-28;google_apis;x86_64"
    
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    
    - name: Run UI Tests
      uses: reactivecircus/android-emulator-runner@v2
      with:
        api-level: 28
        target: google_apis
        arch: x86_64
        profile: Nexus 6
        script: |
          echo "Starting emulator..."
          adb devices
          echo "Waiting for emulator to boot..."
          adb wait-for-device
          echo "Checking boot status..."
          timeout 150 bash -c 'while [[ -z $(getprop sys.boot_completed) ]]; do sleep 1; done;'
          echo "Emulator booted successfully"
          ./gradlew connectedAndroidTest
          echo "Tests completed"
          adb devices
          adb logcat -d
      env:
        ANDROID_EMULATOR_HEADLESS: 1
        ANDROID_EMULATOR_QUICK_BOOT: 1 