name: UI Tests

on:
  pull_request:
    branches: [ main, master ]

jobs:
  test:
    name: Run UI Tests
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: gradle
    
    - name: Set up Android SDK
      uses: android-actions/setup-android@v3
    
    - name: Accept Android Licenses
      run: |
        yes | sdkmanager --licenses
        sdkmanager "platform-tools" "platforms;android-28" "build-tools;28.0.3" "system-images;android-28;google_apis;x86_64"
    
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    
    - name: Run UI Tests
      uses: reactivecircus/android-emulator-runner@v2
      with:
        api-level: 28
        target: google_apis
        arch: x86_64
        profile: Nexus 6
        script: |
          echo "Starting ADB server..."
          adb kill-server
          adb start-server
          adb devices
          
          echo "Starting emulator..."
          adb devices
          echo "Waiting for emulator to boot..."
          adb wait-for-device
          echo "Checking boot status..."
          
          # Wait for boot completion with increased timeout
          timeout 300 bash -c '
            while true; do
              if adb shell getprop sys.boot_completed | grep -q "1"; then
                echo "Emulator booted successfully"
                break
              fi
              echo "Waiting for emulator to boot..."
              sleep 5
            done
          '
          
          echo "Running tests..."
          ./gradlew connectedAndroidTest
          echo "Tests completed"
          adb devices
          adb logcat -d
      env:
        ANDROID_EMULATOR_HEADLESS: 1
        ANDROID_EMULATOR_QUICK_BOOT: 1
        ANDROID_EMULATOR_USE_SYSTEM_LIBS: 1
        ANDROID_EMULATOR_USE_ACCELERATION: 1 